import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/header.tsx'
import PunkList from '../components/punkList.tsx'
import CollectionCard from '../components/collectionCard.tsx'
import Main from '../components/main.tsx'
import { useState, useEffect } from 'react'
import axios from 'axios'
import { ThirdwebSDK } from '@thirdweb-dev/sdk'
import Cors from 'cors'

const sdk = new ThirdwebSDK("rinkeby");
const contract = sdk.getNFTCollection("0x157138C7B970CdfCca3F53eA810aAD52769E5013");

export default function Home() {
  const cors = Cors({
    methods: ['GET', 'HEAD', 'OPTIONS'],
  })
  const [punkListData, setPunkListData] = useState([])
  const [selectedPunk, setSelectedPunk] = useState(0)
  useEffect(() => {
    const getMyNfts = async () => {
      const openseaData = await axios.get(
        'https://testnets-api.opensea.io/assets?asset_contract_address=0x157138C7B970CdfCca3F53eA810aAD52769E5013&order_direction=desc',
        { crossdomain: true }
      )
      console.log(openseaData.data.assets)
      setPunkListData(openseaData.data.assets)
    }
    getMyNfts()
  }, [])

  return (
    <div className="{styles.container}" >
      <Head>
        <title>CryptoPunks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {
        punkListData.length > 0 && (
          <>
          <Main punkListData={punkListData} selectedPunk={selectedPunk}/>
          <PunkList punkListData={punkListData} setSelectedPunk={setSelectedPunk}/>
          </>
        )
      }
    </div> 
  )
}
